use_frameworks!

platform :ios, '8.0'

target 'reponstoryDemo_Example' do
  pod 'reponstoryDemo', :path => '../'

  target 'reponstoryDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
